spring.application.name=ImageConversion
logging.config=classpath:log4j2.xml
server.port=8080

# ??? SpringDoc
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs

# ???????? Swagger UI
springdoc.swagger-ui.enabled=true

# ??? SpringFox
springfox.documentation.swagger-ui.base-url=/swagger-ui

spring.servlet.multipart.enabled=true